#!/bin/bash

shell="$HOME/.scripts/.paths/shell"
                                                         
options=$( awk '{ print $1 }' $shell )
pathToE=$( grep -w "^$1" $shell | awk '{ print $2 }' )

if [ -z "$1" ]; then 
	echo "$options"
else
	alacritty -e v "$pathToE" &>/dev/null &
fi
