#!/bin/sh
 ## test for an existing bus daemon, just to be safe
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
	## if not found, launch a new one
        eval `dbus-launch --sh-syntax`
        echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi

USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

xrdb -load "$HOME"/.config/x11/Xresources
picom -m 1.0 -i 1.0 -e 1.0 --vsync --backend glx --no-fading-openclose &
xwallpaper --zoom "$HOME"/.local/share/bg/BG.png &
#xsetroot -name " " &
urxvtd -q &
dunst &
sxhkd &
unclutter --timeout 1 &
exec bspwm
