#!/bin/bash

configs="$HOME/scripts/.dir/configs"
                                                         
options=$( awk '{ print $1 }' $configs )
pathToE=$( grep "$1" $configs | awk '{ print $2 }' )

if [ -z "$1" ]; then 
	echo "$options"
else
	alacritty -e v "$pathToE" &>/dev/null &
fi
