#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           0
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle true

bspc config click_to_focus true
bspc config focus_follows_pointer false

bspc config ignore_ewmh_focus true

# Colors
bspc config normal_border_color	"#000000"
bspc config active_border_color	"#333333"
bspc config focused_border_color "#333333"
bspc config presel_feedback_color "#aaaaaa"
bspc config urgent_border_color "#bbbbbb"

# DeskTop rules
bspc rule -a Screenkey manage=off
bspc rule -a qemu-system-x86_64 state=fullscreen
bspc rule -a Zathura state=tiled

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a *:Toolkit state=floating sticky=on
bspc rule -a LibreWolf desktop='^2' follow=on
bspc rule -a mpv desktop='^5' follow=on
bspc rule -a Com.github.xournalpp.xournalpp desktop='^5' follow=on
bspc rule -a Signal desktop='^6'
bspc rule -a discord desktop='^6'
bspc rule -a *:www.figma.com desktop='^7' follow=on
bspc rule -a Ld-linux-x86-64.so.2 desktop='^7'
bspc rule -a Gimp-2.10 desktop='^8'
bspc rule -a Gimp desktop='^8'
bspc rule -a qBittorrent desktop='^9'
bspc rule -a obs desktop='^10'

# Games related
bspc rule -a Steam desktop='^8'
bspc rule -a heroic desktop='^8'

bspc rule -a steam_app_0 desktop='^9'
bspc rule -a rocketleague.exe desktop='^9'
bspc rule -a csgo_linux64 desktop='^9'
bspc rule -a PortalWars-Linux-Shipping desktop='^9'
bspc rule -a steam_app_230410 desktop='^9'
bspc rule -a steam_app_714010 desktop='^9'
bspc rule -a JellyBrawl.x86_64 desktop='^9'
bspc rule -a h12_linux desktop='^9'
bspc rule -a "Crab Game.x86_64" desktop='^9'
bspc rule -a steam_app_444090 desktop='^9'
bspc rule -a steam_app_292030 desktop='^9'
bspc rule -a Terraria.bin.x86_64 desktop='^9'
