#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus none
bspc config single_monocle true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#000000"
bspc config active_border_color	"#333333"
bspc config focused_border_color "#333333"
bspc config presel_feedback_color "#aaaaaa"
bspc config urgent_border_color "#bbbbbb"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a Discord desktop='^5'
bspc rule -a obs desktop='^9'
bspc rule -a qemu-system-x86_64 state=fullscreen
