#!/bin/bash

notify="dunstify"
pathBat="~/assets/icons/battery"
pathDate="~/assets/icons/date"
lowI="$pathBat/low.svg"
fullI="$pathBat/full.svg"
chargingI="$pathBat/charging.svg"
saverI="$pathBat/saver.svg"
dateI="$pathDate/date.svg"
clockI="$pathDate/clock.svg"


getStat=$(cat /sys/class/power_supply/BAT0/status)
getCap(){ cat /sys/class/power_supply/BAT0/capacity; }

notifyBat(){ $notify -h string:x-dunst-stack-tag:myBattery -i $1 "Battery level: $(getCap)%"; }

showBat(){
	if [[ $getStat == Unknown ]]
	then
		notifyBat $saverI
	elif [[ $getStat == Charging ]]
	then
		notifyBat $chargingI
	elif [[ $getStat == Discharging ]]
	then
		if (( getCap <= 59 && getCap > 20 ))
		then
			notifyBat $fullI
		else
			notifyBat $lowI
		fi
	fi
}

getDateTxt=$(date "+%A %B %Y")
getDate=$(date "+%D")
getTime=$(date "+%r")
notifyDate(){ $notify -h string:x-dunst-stack-tag:myDate -i $dateI "$getDate" "$getDateTxt"; }
notifyTime(){ $notify -h string:x-dunst-stack-tag:myTime -i $clockI "$getTime"; }
showBat && notifyDate && notifyTime
