#!/bin/bash

# pgrep picom && killall picom || picom -m 1.0 -i 1.0 -e 1.0 --vsync --backend glx --no-fading-openclose &

notify(){ dunstify -h string:x-dunst-stack-tag:picom "$1"; }

killPi(){ killall picom && notify "Picom is dead"; }

pi(){ picom -m 1.0 -i 1.0 -e 1.0 --vsync --backend glx --no-fading-openclose & }
startPi(){ pi && notify "Picom is alive"; }

pgrep picom && killPi || startPi
