#!/bin/bash

notify(){ dunstify "$1"; }

mountnobita(){ sudo ntfs-3g /dev/sdb1 ~/nobita/ && notify "Nobita mounted"; }
umountnobita(){ sudo umount /dev/sdb1 && notify "Nobita unmounted"; }
mountusb(){ sudo mount -o umask=0,uid=nobody,gid=nobody /dev/$1 ~/usb/ && notify "USB mounted"; }
umountusb(){ sudo umount /dev/$1 && notify "USB unmounted"; }

optstring="mubo:"
while getopts ${optstring} opt; do
	case "${opt}" in
		m) mountnobita ;;
		u) umountnobita ;;
		b) 
			shift
			mountusb $1 ;;
		o)
			shift
			umountusb $1 ;;
		*) exit 1 ;;
	esac
done
