#!/bin/bash

#############
#Video Stuff#
#############

myFace(){ ffplay /dev/video0 -loglevel quiet &disown; }
convert(){ ffmpeg -i "$1" -codec copy "$2" ; }

play(){ mpv "$1"; }						#Requires mpv

ytSearch(){ ytfzf -t "$1"; }					#Requires ytfzf
ytPlay(){ ytfzf -a "$1"; }					

optstring="fc:s:p:"

if [[ ! $@ =~ ^\-.+ ]] #checks if there is any arguments
then
  play "$1" ;
else
	while getopts ${optstring} arg; do
		case "${arg}" in 
			f) myFace ;;
			c) 
				shift
				convert "$1" "$2"
				;;
			s)
				shift
				ytSearch "$1"
				;;
			p)
				shift
				ytPlay "$1"
				;;
			*) exit 1 ;;
		esac
	done
fi


#If you want to use ffmpeg for playing video instead of mpv use this

#p(){ ffplay "$1" -loglevel quiet -autoexit; } #Just to play the video

#pws(){ ffplay -vf "subtitles=$1:force_style='FontName=Poppins,Fontsize=24    '" "$2" -loglevel quiet -autoexit; } #Play video with subtitle
