#!/bin/bash

iconPath="~/assets/icons/brands/spotify.svg"

getId=$(pulsemixer --list-sinks | awk '/librespot/ {print $4}' |  sed -e 's/[a-zA-Z]//g' -e 's/[<>,-]//g')

lazy="pulsemixer --id $getId"
getMute=$($lazy --get-mute)
lazyNot="dunstify -h string:x-dunst-stack-tag:spotifydVol"
getVol(){ $lazy --get-volume | awk '{print $1}'; }

notify(){
	case "$1" in
		-c) $lazyNot -i $iconPath "Volume: $(getVol)" -h int:value:$(getVol) ;;
		-m) $lazyNot -i $iconPath "$( [[ $getMute == 0 ]] && echo "Muted" || echo "Unmuted")" ;;
	esac
}

changeVol(){ $lazy --change-volume $1; }
toggleMute(){ $lazy --toggle-mute; }

case "$1" in
	-u) changeVol +2 && notify -c ;;
	-d) changeVol -2 && notify -c ;;
	-m) toggleMute && notify -m;;
esac
