#!/bin/bash

data="playerctl metadata --player=spotifyd -f"
path="~/.cache/albumArt.jpg"
songName(){ $data "{{xesam:title}}"; }
albumArt(){ $data "{{mpris:artUrl}}"; }

function albumImage(){ magick `albumArt` ~/.cache/albumArt.jpg; }
function notify(){ dunstify -h string:x-dunst-stack-tag:song -i $path "`songName`"; }

albumImage && notify
