#!/bin/bash

#Apps
iv="feh"
vv="mpv"
vf="ffplay"
vc="ffmpeg"
vi="magick"
pv="zathura"
te="nvim"
tv="cat"

#Paths
whatImg="$HOME/Downloads/What"*

if [[ "$1" == *.jpeg || "$1" == *.jpg || "$1" == *.png ]]
then
	$iv "$1"
elif [[ "$1" == *.mkv || "$1" == *.mp4 || "$1" == *.gif || "$1" == *.avi || "$1" == *youtu* ]]
then
	$vv "$1"
elif [[ "$1" == *.pdf ]]
then
	$pv "$1" 
else
	case "$1" in
		-a) $iv * ;;
		-w) $iv $whatImg ;;
		-f) $vf /dev/video0 ;;
		-d) 	
			shift
			if [[ "$1" == *.pdf ]]
			then
				$pv "$1" && rm -i "$1"
			else
				$iv $whatImg && rm -I $whatImg
			fi
			;;
		-c)
			shift
			if [[ "$1" == *.mkv ]]
			then
				$vc -i "$1" -codec copy "$2"
			elif [[ "$1" == *.webm ]]
			then
				$ic "$1" "$2"
			fi
			;;
		-v) 
			shift
			$tv "$1"
			;;
		-s)
			shift
			sudo $te "$1"
			;;
		*) $te "$1" ;;
	esac
fi
