#!/bin/bash

app="pulsemixer"
noti="dunstify -h string:x-dunst-stack-tag:audio"
getMute=$($app --get-mute)
path="~/assets/icons/volume"
muteI="$path/mute.svg"
volChangeI="$path/volChange.svg"

getVol(){ $app --get-volume | awk '{print $1}'; }
muteNoti(){
	if [[ $getMute == 0 ]]
	then
		$noti -i "$muteI" "Muted"
	else
		$noti -i "$volChangeI" "Unmuted"
	fi

}

notify(){
	case "$1" in
		-c) $noti -i "$volChangeI" "Volume: $(getVol)" -h int:value:$(getVol) ;;
		-m) muteNoti ;;
	esac
}

volUp(){ $app --change-volume +2 && notify -c; } 
volDown(){ $app --change-volume -2 && notify -c; }
toggleMute(){ $app --toggle-mute && notify -m; }

case "$1" in
	-u) volUp ;;
	-d) volDown ;;
	-m) toggleMute ;;
esac
