[saved_state]
volume = 80

[keybindings]
"=" = "volup"

[theme]
background = "#111111"
primary = "#bbbbbb"
secondary = "#444444"
title = "#aaaaaa"
playing = "#bbbbbb"
playing_selected = "#bbbbbb"
playing_bg = "#444444"
highlight = "#aaaaaa"
highlight_bg = "#444444"
error = "#aaaaaa"
error_bg = "red"
statusbar = "#aaaaaa"
statusbar_progress = "#444444"
statusbar_bg = "#111111"
cmdline = "#aaaaaa"
cmdline_bg = "#111111"
search_match = "#bbbbbb"
