#!/bin/bash

#Icon imports
path="~/assets/icons/storage"
ntfsMntI="$path/ntfsMnt.svg"
ntfsUmntI="$path/ntfsUmnt.svg"
usbMntI="$path/usbMnt.svg"
usbUmntI="$path/usbUmnt.svg"
warningI="~/assets/icons/general/warning.svg"

notify="dunstify"

mountnobita(){ sudo ntfs-3g /dev/sdb1 ~/nobita/ && $notify -i $ntfsMntI "Nobita mounted"; }
ntfsmount(){ sudo ntfs-3g /dev/$1 ~/ntfs/ && $notify -i $ntfsMntI "Ntfs mounted"; }

mountusb(){ sudo mount -o umask=0,uid=nobody,gid=nobody /dev/$1 ~/usb/ && $notify -i $usbMntI "Usb mounted"; }

umountdev(){ sudo umount /dev/$1 ; }

whatp=$(lsblk | awk '/nobita/ || /usb/ || /ntfs/ {print $7}' | sed 's#^.*/##;s/[^_]\+/\L\u&/g')	#Gets the name of the mounted point
whatd=$(lsblk | awk '/nobita/ || /usb/ || /ntfs/ {print $1}' | sed 's/[^\x00-\x7F]//g')			#Gets the mounted point

umountAll(){ 
	if [[ "$whatp" == Nobita || "$whatp" == Ntfs || "$whatp" == Usb ]]
	then
		umountdev $whatd
		if [[ "$whatp" == Nobita || "$whatp" == Ntfs ]]
		then
			$notify -i $ntfsUmntI "$whatp unmounted"
		else
			$notify -i $usbUmntI "Usb unmounted"
		fi
	else
		$notify -i $warningI "No drives mounted" "! nobita || ntfs || usb"
	fi
}

optstring="mu:n:o"
if [[ "$1" =~ - ]]; then
	while getopts ${optstring} opt; do
		case "${opt}" in
			m) mountnobita ;;
			u) 
				shift
				mountusb $1 ;;
			n)	
				shift
				ntfsmount $1 ;;
			o)
				shift
				umountAll ;;
			*) exit 1 ;;
		esac
	done
else 
	echo "Enter a valid option" | lolcat
fi
