#!/bin/bash

app="pulsemixer"
noti="dunstify -h string:x-dunst-stack-tag:audio"
getMute=$($app --get-mute)
path="~/assets/icons/volume"
muteI="$path/mute.svg"
volChangeI="$path/volChange.svg"
warningI="~/assets/icons/general/warning.svg"

getVol(){ $app --get-volume | awk '{print $1}'; }
muteNoti(){
	if [[ $getMute == 0 ]]
	then
		$noti -i $muteI "Muted"
	else
		$noti -i $volChangeI "Unmuted"
	fi

}

notify(){
	case "$1" in
		-c) $noti -i $volChangeI "Volume: $(getVol)" -h int:value:$(getVol) ;;
		-m) muteNoti ;;
	esac
}

changeVol(){ 
	if [[ $getMute == 0 ]]
	then
		$app --change-volume $1 && notify -c 
	else
		$noti -i $warningI "Audio is muted" "Unmute to change volume"
	fi
}

toggleMute(){ $app --toggle-mute && notify -m; }

case "$1" in
	-u) changeVol +2 ;;
	-d) changeVol -2 ;;
	-m) toggleMute ;;
esac
