add_newline = false

[character]
success_symbol='[>](bold green)'
error_symbol='[x](bold red)'
vimcmd_symbol='[v](bold green)'
vimcmd_replace_one_symbol='[v](bold purple)'
vimcmd_replace_symbol='[v](bold purple)'
vimcmd_visual_symbol='[v](bold yellow)'
